kodecocodes/swift-algorithm-club

Queue/Queue.playground/Contents.swift
Queue/Queue.playground/contents.xcplayground
Queue/Queue.playground/timeline.xctimeline
Stack/Stack.playground/Contents.swift
Stack/Stack.playground/contents.xcplayground
Stack/Stack.playground/timeline.xctimeline

Added playgrounds with comments for Stack and Queue.

Added playgrounds with comments

---

Mergesort/Mergesort.playground/Contents.swift
Mergesort/Mergesort.playground/contents.xcplayground
Mergesort/Mergesort.playground/timeline.xctimeline
Mergesort/Mergesort.swift
Mergesort/README.markdown
README.markdown

Let me know if this looks right!

Merge sort stuffs

---

Select Minimum Maximum/MinimumMaximumPairs.swift
Select Minimum Maximum/README.markdown
Select Minimum Maximum/SelectMinimumMaximum.playground/Contents.swift

Thanks for the link to http://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/ :smiley:
I've added my implementation in Swift. Let me know if you see something I can improve/change.

Select min and max but doing only 3 comparisons for every 2 items

---

Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximum.xcodeproj/project.pbxproj
Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/MaximumTests.swift
Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/MinimumTests.swift
Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/SelectMinimumMaximumTests.swift
Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/TestHelper.swift

Added tests that compare the algorithm against the Swift library algorithm.
Also fixed some typos in the test names.

Checking algorithm against Swift library algorithm

---

Stack/Stack.playground/Contents.swift

To make the queue playground example consistent with the other file.

Replaced count == 0 with isEmpty

---

Fizz Buzz/FizzBuzz.playground/Contents.swift
Fizz Buzz/FizzBuzz.playground/contents.xcplayground
Fizz Buzz/FizzBuzz.playground/timeline.xctimeline
Fizz Buzz/FizzBuzz.swift
Fizz Buzz/README.markdown
README.markdown

Added fizz buzz puzzle to list of interview puzzles.

Added fizz buzz

---

Binary Search Tree/README.markdown

[From the docs](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/BasicOperators.html#//apple_ref/doc/uid/TP40014097-CH6-ID72)

change null-coalescing to nil-coalescing

---

Stack/Stack.swift

Add SequenceType conformance to Stack

---

B Tree/README.markdown

Title says it all. Fun project to work on.

Add B-tree paragraph placeholder

---

Shunting Yard/README.markdown
Shunting Yard/Shunting Yard.playground/Contents.swift
Shunting Yard/Shunting Yard.playground/Sources/Stack.swift
Shunting Yard/Shunting Yard.playground/contents.xcplayground
Shunting Yard/Shunting Yard.playground/timeline.xctimeline
Shunting Yard/ShuntingYardAlgorithm.swift
Shunting Yard/Stack.swift

Details on the algorithm are here: https://en.wikipedia.org/wiki/Shunting-yard_algorithm
Todo list:

Shunting yard algorithm

---

AVL Tree/Tests/AVLTreeTests.swift

Tests to cover:
- minimum node
- successor of a node
- delete a node given a key

More test cases for AVLTree

---

Linked List/LinkedList.swift
Linked List/README.markdown

Refactor reverse method of LinedList class to make the code more Swift-like, without the forced unwrapping.

Refactor linked list

---

AVL Tree/AVLTree.playground/Contents.swift
AVL Tree/AVLTree.playground/Sources/AVLTree.swift
AVL Tree/AVLTree.swift
AVL Tree/Tests/AVLTreeTests.swift
AVL Tree/Tests/TreeNodeTests.swift

(This pull request is to replace #80. It contains code style fix which #80 didn't follow)
- Tree rotation was replaced by updating links of the tree structure
- Removed irrelevant test cases
On March 16:
* Fixed indentation to match repo's coding style

Fixed AVL Tree bug

---

AVL Tree/AVLTree.playground/Sources/AVLTree.swift
AVL Tree/AVLTree.swift
AVL Tree/Tests/AVLTreeTests.swift

AVL Tree bug fix:
- Fixed a bug in delete where it will not balance the tree after tree deletion.
AVL Tree test:
- Removed test cases for duplicate keys
- Check tree balance for each insert and delete
- Check tree size for each insert and delete

added more test cases to test the validity of the AVL Tree

---

K-Means/KMeans.swift
K-Means/Tests/KMeansTests.swift
K-Means/Tests/Tests.xcodeproj/project.pbxproj

This could help showing how to use KMeans as a classifier.
Some changes to KMeans properties and function.
Updated Tests accordingly.
Demo the usage of labels in one small test.

Introduce Associated Labels to centroids.

---

Queue/README.markdown

Make it same as explanation, i.e at least 50 elements and 0.25 percent.

Fixed the count condition 

---

Combinatorics/Combinatorics.playground/Contents.swift
Combinatorics/README.markdown

Add a faster approach to calculate `C(n, k)` in `O(k) time and `O(1)`
extra space.

Add a faster approach to calculate C(n, k)

---

Counting Sort/CountingSort.playground/Contents.swift
Counting Sort/CountingSort.playground/contents.xcplayground
Counting Sort/CountingSort/CountingSort.swift
Counting Sort/CountingSort/CountingSort.xcodeproj/project.pbxproj
Counting Sort/CountingSort/CountingSort/CountingSortTest.swift
Counting Sort/CountingSort/CountingSort/Info.plist
Counting Sort/README.markdown

Counting sort

---

Boyer-Moore/README.markdown
Graph/README.markdown
Linked List/README.markdown

Hi @hollance and Swift algorithm club team,
I found and fixed a few code snippets and typo. Please review this PR when you have time.
Thank you for creating and maintaining this amazing project. I am learning a lot from this repo!

Fix code snippet and typo

---

README.markdown

This a great tool to visualize algorithms, check it out: http://jasonpark.me/AlgorithmVisualizer/
:]

Adds AlgorithmVisualizer to README

---

Bounded Priority Queue/BoundedPriorityQueue.playground/Contents.swift
Bounded Priority Queue/BoundedPriorityQueue.playground/Sources/BoundedPriorityQueue.swift
Bounded Priority Queue/BoundedPriorityQueue.playground/contents.xcplayground
Bounded Priority Queue/BoundedPriorityQueue.playground/playground.xcworkspace/contents.xcworkspacedata
Bounded Priority Queue/README.markdown
Bounded Priority Queue/Tests/BoundedPriorityQueueTests.swift

Added updated implementation from Matthijs.
Updated readme and tests to reflect updated implementation.
This is a rough draft. I will review in the morning.

Bounded Priority Queue - adding updated implementation

---

Minimum Edit Distance/MinimumEditDistance.swift
Minimum Edit Distance/README.markdown

Hi! 
I implemented the usual minimum edit distance algorithm for strings using the Levenshtein distance. I also plan to extend this implementation such that the algorithm can use arbitrary distance measures (as for example keyboard lookup tables).

Minimum edit distance for strings

---

Treap/Treap.swift
Treap/Treap/Treap.xcodeproj/project.pbxproj
Treap/Treap/Treap/AppDelegate.swift
Treap/Treap/Treap/Assets.xcassets/AppIcon.appiconset/Contents.json
Treap/Treap/Treap/Base.lproj/MainMenu.xib
Treap/Treap/Treap/Info.plist
Treap/Treap/TreapTests/Info.plist
Treap/Treap/TreapTests/TreapTests.swift
Treap/TreapCollectionType.swift
Treap/TreapMergeSplit.swift

So, this is not pretty and does not (yet) contain much in the way of teachable moments or explanations, but here it is anyway. Bonus includes conformance to `CollectionType`!

Treap using Indirect Enums

---

README.markdown

Thought it would be good to list you guys on the page somewhere! Feel free to tweak.

Giving credit to Matthijs, Chris, Kelvin, and contributors :]

---

swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Using a workspace brings all of the projects together in a single window with all of the code highlighting, search and documentation features that Xcode brings. I found it extremely useful when viewing/comparing multiple projects.

Added swift-algorithm-cllub.workspace so all projects can be viewed together

---

Fizz Buzz/README.markdown

Fix for #141

---

README.markdown

@kelvinlauKL Sorry, I've forgotten to include this in pull request #151.

Fixed link to B-Tree in README.md

---

Set Cover (Unweighted)/README.markdown
Set Cover (Unweighted)/SetCover.playground/Contents.swift
Set Cover (Unweighted)/SetCover.playground/Sources/RandomArrayOfSets.swift
Set Cover (Unweighted)/SetCover.playground/Sources/SetCover.swift
Set Cover (Unweighted)/SetCover.playground/contents.xcplayground
Set Cover (Unweighted)/SetCover.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

I've written the code for the Greedy Set Cover algorithm (unweighted), and I'm starting to work on the explanation in the README.
I'll let you know when I'm done (hopefully within one week).

Set Cover (Unweighted)

---

Set Cover (Unweighted)/SetCover.playground/Sources/SetCover.swift
Set Cover (Unweighted)/SetCover.playground/playground.xcworkspace/contents.xcworkspacedata
Set Cover (Unweighted)/SetCover.swift
Under Construction.markdown

Added link on under construction page. Replaced count == 0 with isEmpty.

Set cover unweighted link

---

Palindromes/Palindromes.playground/Contents.swift
Palindromes/Palindromes.playground/contents.xcplayground
Palindromes/Palindromes.swift
Palindromes/README.markdown

I've seen Palindrome Checking Algorithm questions in programming interviews before, and thought it would be a nice, quick addition to the Puzzle section here.

Palindrome Checking Algorithm

---

Tree/Tree.swift

Add public access in Tree.swift.

Add public access in Tree

---

Comb Sort/Comb Sort.playground/Contents.swift
Comb Sort/Comb Sort.playground/contents.xcplayground
Comb Sort/Comb Sort.playground/playground.xcworkspace/contents.xcworkspacedata
Comb Sort/Comb Sort.swift
Comb Sort/README.markdown

Added the files for Comb Sort, a more time efficient version of Bubble Sort. Let me know how it looks, and if there is anything to update/change (and why preferably 👍).

Added Comb Sort

---

Bubble Sort/README.markdown

Added the runtime, memory and a better description of bubble sort. The implementation was not added but it is good to know the concept.
Even if the algorithm is "horrible" a description of it should be added for developers to grasp the concept of bubble sort. Bubble sort is a very common sorting technique taught when beginning to learn sorting algorithms. I do believe the algorithm should be implemented and shown but that is a change for another day.

Updated Bubble Sort description

---

Palindromes/Palindromes.playground/Contents.swift
Palindromes/Palindromes.swift

Fixing compiler error when opening Palindromes project in Xcode beta 8

Palindromes swift3

---

.travis.yml
Insertion Sort/InsertionSort.playground/Contents.swift
Insertion Sort/InsertionSort.swift
Insertion Sort/README.markdown
Insertion Sort/Tests/Tests.xcodeproj/project.pbxproj
Insertion Sort/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Quicksort/Tests/SortingTestHelpers.swift

Updating Insertion Sort to Swift 3

---

.travis.yml
B-Tree/BTree.playground/Contents.swift
B-Tree/BTree.playground/Sources/BTree.swift
B-Tree/BTree.swift
B-Tree/README.md
B-Tree/Tests/Tests.xcodeproj/project.pbxproj
B-Tree/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
B-Tree/Tests/Tests/BTreeNodeTests.swift
B-Tree/Tests/Tests/BTreeTests.swift

I will let you know when I'm ready for review.

Updating B-Tree to Swift 3

---

.travis.yml
Selection Sort/README.markdown
Selection Sort/SelectionSort.playground/Contents.swift
Selection Sort/SelectionSort.swift
Selection Sort/Tests/Tests.xcodeproj/project.pbxproj
Selection Sort/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

Update Selection Sort to Swift 3

---

Binary Search Tree/Solution 1/BinarySearchTree.playground/Contents.swift
Binary Search Tree/Solution 1/BinarySearchTree.playground/Sources/BinarySearchTree.swift
Binary Search Tree/Solution 2/BinarySearchTree.playground/Contents.swift
Binary Search Tree/Solution 2/BinarySearchTree.playground/Sources/BinarySearchTree.swift

Binary search tree swift3

---

Fizz Buzz/FizzBuzz.playground/Contents.swift
Fizz Buzz/FizzBuzz.playground/playground.xcworkspace/contents.xcworkspacedata
Fizz Buzz/FizzBuzz.playground/timeline.xctimeline
Fizz Buzz/FizzBuzz.swift
Fizz Buzz/README.markdown

This is my very first try with swift
part of #181

updated fizzBuzz to swift3

---

Deque/Deque-Optimized.swift
Deque/Deque-Simple.swift
Deque/Deque.playground/Contents.swift
Deque/Deque.playground/timeline.xctimeline
Deque/README.markdown

deque update to swift 3

---

Breadth-First Search/BreadthFirstSearch.playground/Pages/Simple example.xcplaygroundpage/Contents.swift
Breadth-First Search/BreadthFirstSearch.playground/Pages/Simple example.xcplaygroundpage/timeline.xctimeline
Breadth-First Search/BreadthFirstSearch.playground/Sources/Edge.swift
Breadth-First Search/BreadthFirstSearch.playground/Sources/Graph.swift
Breadth-First Search/BreadthFirstSearch.playground/Sources/Node.swift
Breadth-First Search/BreadthFirstSearch.playground/Sources/Queue.swift
Breadth-First Search/BreadthFirstSearch.swift
Breadth-First Search/README.markdown

migrating bfs to swift3

---

Brute-Force String Search/BruteForceStringSearch.playground/Contents.swift
Brute-Force String Search/BruteForceStringSearch.playground/timeline.xctimeline
Brute-Force String Search/BruteForceStringSearch.swift
Brute-Force String Search/README.markdown

Migrating Brute Force String Search to Swift3

---

Monty Hall Problem/MontyHall.playground/Contents.swift
Monty Hall Problem/MontyHall.playground/timeline.xctimeline

migrating montyhall to swift 3

---

Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.swift
Linked List/Tests/LinkedListTests.swift

This is my first contribution to the repo, let me know if something should be added :)

Migrate Linked List to Swift 3.0

---

Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.swift

I added a public init so this can be used in a Playground. I also added
an extension to create a linked list from an array of values.

Added public init and array init

---

Slow Sort/README.markdown
Slow Sort/SlowSort.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

I have added another ineffective algorithm as sorting algorithm example.

Added SlowSort

---

Boyer-Moore/BoyerMoore.playground/Contents.swift
Boyer-Moore/BoyerMoore.playground/timeline.xctimeline
Boyer-Moore/README.markdown

The purpose of this PR is to update the Boyer Moore algorithm to Swift 3.  This mostly consisted of correcting the updates to index wrangling.  No passive aggressive comments please.

Boyer moore swift3

---

README.markdown

Add Swift Structures to the repository list

Added Swift Structures to repository list

---

Shell Sort/Tests/Tests.xcodeproj/project.pbxproj
Shell Sort/shellsort.swift

I updated Shell Sort to Swift 3.0. This is my first time contributing to open source so please bear with me if I made any mistakes.

Update to Swift 3.0

---

.travis.yml
Topological Sort/Graph.swift
Topological Sort/Tests/Tests.xcodeproj/project.pbxproj
Topological Sort/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Topological Sort/Tests/TopologicalSortTests.swift
Topological Sort/Topological Sort.playground/Sources/Graph.swift
Topological Sort/Topological Sort.playground/Sources/TopologicalSort1.swift
Topological Sort/Topological Sort.playground/Sources/TopologicalSort3.swift
Topological Sort/TopologicalSort1.swift
Topological Sort/TopologicalSort3.swift

#181. This is my first contribution to this repo. Suggestions are welcome. :)

Migrated Topological Sort to Swift 3

---

Selection Sampling/SelectionSampling.playground/Contents.swift
Selection Sampling/SelectionSampling.playground/timeline.xctimeline

I took off an extra min in the your random function. This is my first open source contribution!! Ever!

took off an extra min

---

Linear Regression/LinearRegression.playground/Contents.swift
Linear Regression/README.markdown

- Migrated **Linear Regression** for #181.
- Made minor style tweaks in code and `README.md`.

Swift 3 Migration: Linear Regression

---

B-Tree/README.md

fixed typos in B-Tree README

---

Karatsuba Multiplication/README.markdown

(a+b)*(c+d) - a*c - b*c  = (a*c + a*d + b*c + b*d) - a*c - b*c
should be
(a+b)*(c+d) - a*c - b*d  = (a*c + a*d + b*c + b*d) - a*c - b*d

Fix mistake in the formula that simplifies to (a*d + b*c)

---

Binary Tree/BinaryTree.playground/Contents.swift
Binary Tree/BinaryTree.swift
Binary Tree/README.markdown

In Binary Tree, updated enum case style.
Also, updated README in Binary Tree.

Update enum case style in Binary Tree

---

README.markdown

Fix Skip-List link in readme;

---

README.markdown

Add missing link and description of Trie in README.

Add missing link for Trie in README.

---

Boyer-Moore/BoyerMoore.playground/Contents.swift
Boyer-Moore/BoyerMoore.playground/timeline.xctimeline
Boyer-Moore/BoyerMoore.swift
Boyer-Moore/README.markdown

Updated to Swift 3 Syntax.
The .swift file wasn’t converted prior to my commit. Additionally, I fixed a bug there.

Updated to Swift 3.

---

AVL Tree/AVLTree.swift

Fix Access Control position based on [raywenderlich/swift-style-guide#access-control](https://github.com/raywenderlich/swift-style-guide#access-control).

Fix Access Control position in AVLTree

---

Red-Black Tree/README.markdown

Add each step title for clarity.

Make each steps clear

---

README.markdown

This book is different from other algorithms books for its rich illustrations. It's immensely helpful for those who are visual learner like myself.

Added a new algorithms book under "Learn More"

---

Merge Sort/MergeSort.playground/Contents.swift
Merge Sort/MergeSort.swift

I upgraded the "**mergeSort**" & "**merge**" function in the _Merge Sort Algorithm_ to make it generic if someone needed to use the recursive approach for this algorithm.

Generic Functions for Merge Sort (Recursive)

---

.travis.yml
All-Pairs Shortest Paths/APSP/APSP.xcodeproj/project.pbxproj
All-Pairs Shortest Paths/APSP/APSP.xcodeproj/xcshareddata/xcschemes/APSP.xcscheme
All-Pairs Shortest Paths/APSP/APSP.xcodeproj/xcshareddata/xcschemes/APSPTests.xcscheme
All-Pairs Shortest Paths/APSP/APSP/APSP.swift
All-Pairs Shortest Paths/APSP/APSP/FloydWarshall.swift
All-Pairs Shortest Paths/APSP/APSP/Helpers.swift
All-Pairs Shortest Paths/APSP/APSPTests/APSPTests.swift

Success 🎉  
This PR is what was intended in #346 but that one got mixed with #344 sooo...
Hope it is useful.

Migrates All-Pairs Shortest Paths to Swift3 syntax

---

Linked List/LinkedList.swift

Useful for manipulating linked lists and you already have node objects

+ methods to append, insert, remove node objects

---

DiningPhilosophers/DiningPhilosophers.xcodeproj/project.pbxproj
DiningPhilosophers/DiningPhilosophers.xcodeproj/project.xcworkspace/contents.xcworkspacedata
DiningPhilosophers/DiningPhilosophers.xcodeproj/xcshareddata/xcschemes/DiningPhilosophers.xcscheme
DiningPhilosophers/DiningPhilosophers.xcodeproj/xcshareddata/xcschemes/xcschememanagement.plist
DiningPhilosophers/LICENSE
DiningPhilosophers/Package.swift
DiningPhilosophers/README.md
DiningPhilosophers/Sources/main.swift

Dining philosophers problem Algorithm implemented in Swift (concurrent algorithm design to illustrate synchronization issues and techniques for resolving them using GCD and Semaphore in Swift)
From https://en.wikipedia.org/wiki/Dining_philosophers_problem
In computer science, the dining philosophers problem is an example problem often used in concurrent algorithm design to illustrate synchronization issues and techniques for resolving them.
It was originally formulated in 1965 by Edsger Dijkstra as a student exam exercise, presented in terms of computers competing for access to tape drive peripherals. Soon after, Tony Hoare gave the problem its present formulation.
This Swift implementation is based on the Chandy/Misra solution and it uses GCD Dispatch and Semaphone on Swift cross …

Dining Philosophers Problem Algorithm

---

Counting Sort/CountingSort.swift

Update CountingSort.swift to Swift 3.0 syntax

---

Shell Sort/ShellSortExample.swift

add file ShellSortExample.swift

---

Convex Hull/Convex Hull.xcodeproj/project.pbxproj
Convex Hull/Convex Hull.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Convex Hull/Convex Hull/AppDelegate.swift
Convex Hull/Convex Hull/Assets.xcassets/AppIcon.appiconset/Contents.json
Convex Hull/Convex Hull/Base.lproj/LaunchScreen.storyboard
Convex Hull/Convex Hull/Info.plist
Convex Hull/Convex Hull/View.swift
Convex Hull/README.md

Convex hull

---

Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.swift
Linked List/Tests/LinkedListTests.swift

The Linked List data structure now conforms with the ExpressibleByArrayLiteral. For more details [here](https://developer.apple.com/reference/swift/expressiblebyarrayliteral)

Added ExpressibleByArrayLiteral to the Linked List and Tests

---

Quicksort/README.markdown

I think there's typos in README.md of QuickSort :(

Modified typo in README.md of QuickSort

---

DiningPhilosophers/Sources/main.swift

Couldn't run without adding an availability check

availability check, native array loop for signal

---

README.markdown

fixed broken link in README.markdown

fixed broken link

---

Binary Tree/README.markdown

Just need to convert spaces into %20 for relative URLs
with spaces to work.

Fix binary search tree link

---

README.markdown

Super simple but just something I noticed while getting started.
Cheers!

Update How to Contribute link on README

---

Big-O Notation.markdown

Fixed the link to "merge sort".

Update Big-O Notation.markdown

---

Heap/README.markdown

Another PR to fix white-space encoding in Markdown links.

Updated Heap/README.markdown

---

AVL Tree/README.markdown
Bounded Priority Queue/README.markdown
Count Occurrences/README.markdown
Depth-First Search/README.markdown
Deque/README.markdown
Heap Sort/README.markdown
Huffman Coding/README.markdown
Knuth-Morris-Pratt/README.markdown
Kth Largest Element/README.markdown
Minimum Spanning Tree (Unweighted)/README.markdown
Priority Queue/README.markdown
Quicksort/README.markdown
Segment Tree/README.markdown
Selection Sort/README.markdown

fix broken links containing whitespaces

fix: broken links

---

Binary Search Tree/README.markdown
Shell Sort/ShellSortExample.swift

Updated README.markdown

---

DiningPhilosophers/README.md

Revisions in README.md

---

Array2D/README.markdown

I have revised your document to be simplified and concise.

Revisions in README.markdown

---

.travis.yml
Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.playground/contents.xcplayground
Linked List/LinkedList.swift
Linked List/README.markdown
Linked List/Tests/LinkedListTests.swift

This PR adds  the following enhancements/corrections to the Linked List files:
1. (README.markdown) Update a comment about Swift's ability to add nested classes.
2. (README.markdown) Added/removed some blank lines to emphasize on separate sections.
3. (README.markdown) Updated the signature at the end of the file to reflect the community contributions.
4. (LinkedList.swift) Moved the node declaration to be nested inside the `LinkedList` class as per the norm of Data Structures design.
5. (LinkedList.swift #429) Added 2 overloaded versions of `insert` & `append` functions where both can take a Linked List as an argument.
6. (LinkedList.playground #429) Added the changes from previous point (5) with few lines at the end to demo the changes.
7. (LinkedList.playground) Added standard & …

Various Enhancements on the Linked List files

---

AVL Tree/AVLTree.swift

prettify some syntax around optionals

---

Ternary Search Tree/TST.playground/Sources/TernarySearchTree.swift
Ternary Search Tree/TernarySearchTree.swift

Fixes swiftlint warning: "MARK comment should be in valid format."

[swiftlint] Fix: "MARK comment should be in valid format."

---

Hash Table/README.markdown

changed enumerate() -> enumerated()
I found modified method name `enumerate()`. So I changed new method name `enumerated()`

Change modified method name

---

Tree/README.markdown

Fixes alignment by adding an additional tab

Fix alignment by adding an additional tab

---

Trie/ReadMe.md

Fixes a misindented return statement

Fix misindented return statement

---

Heap/README.markdown

Fix broken links by replacing spaces with %20

Fix broken links by replacing spaces with %20

---

Graph/README.markdown

Fix minor grammar typo

---

Radix Sort/ReadMe.md

Github seems to require spaces between "#" and headings .

Formatted headers in readme

---

Heap/README.markdown

Fix a few typos in Heap/README

Fix a few typos in Heap/README

---

Heap Sort/README.markdown

Update displayed code to use 2 space indentation

Update displayed code to use 2 space indentation

---

Linear Regression/README.markdown

Just a few minor typo fixes and markdown formatting for headlines.

Fix typos and markdown formatting

---

Convex Hull/README.md

Just a minor typo fix and style change.

Fix minor typo

---

Algorithm Design.markdown

Added description for Divide and Conquer section.
Added brief description for Divide and Conquer section.

Divide and Conquer

---

Ordered Array/README.markdown

Link'n to  production ready implementations is a good idea.

Add links to Ole Begemann's quite nice SortedArray.

---

Hash Table/README.markdown

There was a typo in the line that has been changed. The sentence itself has been altered slightly to accommodate the fix for the typo and maintain clarity.

Updated README for clarity

---

Ordered Set/AppleOrderedSet.playground/Contents.swift
Ordered Set/AppleOrderedSet.playground/Sources/AppleOrderedSet.swift
Ordered Set/AppleOrderedSet.playground/contents.xcplayground
Ordered Set/AppleOrderedSet.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

https://developer.apple.com/documentation/foundation/nsmutableorderedset
In this repo, the ordered set is actually not the right apple library ordered set. So, I write the one exactly the same as Apple one.

Ordered Set - Apple Version

---

Fizz Buzz/FizzBuzz.playground/Contents.swift

Tested Playground with Xcode 9.0b4.

Updated for Swift 4 Xcode 9b4

---

Stack/Stack.playground/Contents.swift

The Swift stack implementation has been tested on Xcode 9 b4 and works as expected and the unit tests pass as well.

update Stack implementation to Swift 4 with Xcode 9b4

---

Palindromes/Palindromes.playground/Contents.swift

Palindrome implementation has been tested on Xcode 9 b4 and works as expected and the unit tests pass as well.

update palindrome implementation to Swift 4 with Xcode 9b4

---

GCD/GCD.playground/Contents.swift

GCD implementation has been tested on Xcode 9 b4 and works as expected and the unit tests pass as well.

update gcd implementation to Swift 4 with Xcode 9b4

---

Queue/Queue.playground/Contents.swift

Queue implementation has been tested on Xcode 9 b4 and works as expected and the unit tests pass as well.

Queue-swift4

---

Two-Sum Problem/README.markdown
Two-Sum Problem/Solution 1/2Sum.playground/Contents.swift
Two-Sum Problem/Solution 2/2Sum.playground/Contents.swift
Two-Sum Problem/Solution 2/2Sum.playground/timeline.xctimeline

[Swift4 Migration] claim TwoSum problem

---

Boyer-Moore/BoyerMoore.playground/Contents.swift
Boyer-Moore/Tests/Tests.xcodeproj/project.pbxproj
Boyer-Moore/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Count Occurrences/CountOccurrences.playground/Contents.swift
Count Occurrences/CountOccurrences.playground/timeline.xctimeline
Fixed Size Array/FixedSizeArray.playground/Contents.swift

Update Count Occurrences and Fixed Size Array to Swift 4

Swift4 update to Count Occurrences and Fixed Size Array

---

Heap Sort/HeapSort.swift
Heap Sort/Tests/HeapSortTests.swift
Heap Sort/Tests/Tests.xcodeproj/project.pbxproj
Heap/Heap.swift

Update Heap Sort to Swift 4
#507

[Swift 4] Update Heap Sort

---

Heap/Heap.swift
Heap/Tests/HeapTests.swift
Heap/Tests/Tests.xcodeproj/project.pbxproj
Heap/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

[Swift 4] Update Heap

---

Shuffle/Shuffle.playground/Contents.swift
Shuffle/Shuffle.playground/Sources/Shuffle.swift
Shuffle/Shuffle.playground/timeline.xctimeline
Shuffle/Shuffle.swift

Update Shuffle to Swift 4
#507

[Swift 4] Update Shuffle to Swift 4

---

Union-Find/UnionFind.playground/Contents.swift

Update Union Find to Swift 4
#507

[Swift 4] Update Union Find

---

Selection Sort/SelectionSort.playground/Contents.swift
Selection Sort/SelectionSort.playground/Sources/SelectionSort.swift
Selection Sort/SelectionSort.playground/timeline.xctimeline
Selection Sort/SelectionSort.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Update Selection Sort to Swift 4
#507

[Swift 4] Update Selection Sort

---

Array2D/Array2D.playground/Contents.swift

Update Array2D to Swift 4
#507

[Swift 4] Update Array2D

---

Trie/Trie/Trie/Trie.swift
Trie/Trie/Trie/ViewController.swift
Trie/Trie/TrieTests/TrieTests.swift

[Swift 4] Update Trie

---

Tree/Tree.playground/Contents.swift
Tree/Tree.playground/Sources/Tree.swift
Tree/Tree.playground/timeline.xctimeline
Tree/Tree.swift

[Swift 4] Update Tree

---

Topological Sort/Topological Sort.playground/Contents.swift
Topological Sort/Topological Sort.playground/timeline.xctimeline

Update Topological Sort to Swift 4
#507

[Swift 4] Update Topological Sort

---

Depth-First Search/DepthFirstSearch.playground/Pages/Simple Example.xcplaygroundpage/Contents.swift

[Swift 4] Update DFS

---

Breadth-First Search/BreadthFirstSearch.playground/Pages/Simple example.xcplaygroundpage/Contents.swift

[Swift 4] Update BFS

---

Segment Tree/SegmentTree.playground/Contents.swift

Update Segment Tree to Swift 4
#507

[Swift 4] Update Segment Tree

---

Linked List/LinkedList.playground/Contents.swift
Linked List/Tests/LinkedListTests.swift
Linked List/Tests/Tests.xcodeproj/project.pbxproj

Update Linked List to Swift 4
#507

[Swift 4] Update Linked List

---

Merge Sort/MergeSort.playground/Contents.swift
Merge Sort/MergeSort.playground/timeline.xctimeline

Update Merge Sort to Swift 4
#507

[Swift 4] Update Merge Sort

---

Binary Search/BinarySearch.playground/Contents.swift
Binary Search/BinarySearch.playground/timeline.xctimeline

Update Binary Search to Swift 4
#507

[Swift 4] Update Binary Search

---

Binary Search Tree/Solution 1/BinarySearchTree.playground/Contents.swift
Binary Search Tree/Solution 1/BinarySearchTree.playground/timeline.xctimeline
Binary Search Tree/Solution 2/BinarySearchTree.playground/Contents.swift
Binary Search Tree/Solution 2/BinarySearchTree.playground/timeline.xctimeline

Update Binary Search Tree to Swift 4
#507

[Swift 4] Update Binary Search Tree

---

Binary Tree/BinaryTree.playground/Contents.swift

Update Binary Tree to Swift 4
#507

[Swift 4] Update Binary Tree

---

Huffman Coding/Huffman.playground/Contents.swift
Huffman Coding/Huffman.playground/Sources/Heap.swift
Huffman Coding/Huffman.playground/timeline.xctimeline

Update Huffman Coding to Swift 4
#507

[Swift 4] Update Huffman Coding

---

Counting Sort/CountingSort.playground/Contents.swift

Update Counting Sort to Swift 4
#507

[Swift 4] Update Counting Sort

---

Deque/Deque.playground/Contents.swift

[Swift 4] Update Deque

---

Hash Set/HashSet.playground/Contents.swift
Hash Set/HashSet.playground/timeline.xctimeline
Hash Table/HashTable.playground/Contents.swift

#507 HashSet Updated to Swift4

Hash set Swift4

---

Ordered Array/OrderedArray.playground/Contents.swift
Ordered Array/OrderedArray.playground/timeline.xctimeline

Update Ordered Array to Swift 4
#507

[Swift 4] Update Ordered Array

---

All-Pairs Shortest Paths/APSP/APSP.playground/Contents.swift
All-Pairs Shortest Paths/APSP/APSP.playground/timeline.xctimeline
All-Pairs Shortest Paths/APSP/APSP.xcodeproj/project.pbxproj
All-Pairs Shortest Paths/APSP/APSPTests/APSPTests.swift
Graph/GraphTests/GraphTests.swift

Update All Pairs Shortest Paths to Swift 4
#507

[Swift 4] Update All Pairs Shortest Paths

---

Brute-Force String Search/BruteForceStringSearch.playground/Contents.swift

Update Brute Force String Search to Swift 4
#507

[Swift 4] Update Brute Force String Search

---

Insertion Sort/InsertionSort.playground/Contents.swift
Insertion Sort/InsertionSort.playground/timeline.xctimeline

Update Insertion Sort to Swift 4
#507

[Swift 4] Update Insertion Sort

---

Bounded Priority Queue/BoundedPriorityQueue.playground/Contents.swift

Update Bounded Priority Queue to Swift 4
#507

[Swift 4] Update Bounded Priority Queue

---

Combinatorics/Combinatorics.playground/Contents.swift
Combinatorics/Combinatorics.playground/timeline.xctimeline

[Swift 4] Update Combinatorics

---

Convex Hull/Convex Hull.xcodeproj/project.pbxproj
Convex Hull/Convex Hull/View.swift

Update Convex Hull to Swift 4
#507

[Swift 4] Update Convex Hull

---

DiningPhilosophers/DiningPhilosophers.xcodeproj/project.pbxproj
DiningPhilosophers/Sources/main.swift

Update Dining Philosophers to Swift 4
#507

[Swift 4] Update Dining Philosophers

---

K-Means/Tests/KMeansTests.swift
K-Means/Tests/Tests.xcodeproj/project.pbxproj

[Swift 4] Update KMeans

---

Kth Largest Element/kthLargest.playground/Contents.swift
Kth Largest Element/kthLargest.playground/Sources/kthLargest.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Update Kth Largest Element to Swift 4
#507

[Swift 4] Update Kth Largest Element

---

Depth-First Search/DepthFirstSearch.playground/Pages/Simple Example.xcplaygroundpage/Contents.swift
Depth-First Search/DepthFirstSearch.playground/Sources/Edge.swift
Depth-First Search/DepthFirstSearch.playground/Sources/Graph.swift
Depth-First Search/DepthFirstSearch.playground/Sources/Node.swift
Depth-First Search/Tests/DepthFirstSearchTests.swift
Depth-First Search/Tests/Tests.xcodeproj/project.pbxproj

#507 Updated DepthFirstSearch to Swift4

Depth first search Swift4

---

Treap/Treap/Treap.xcodeproj/project.pbxproj
Treap/Treap/TreapTests/TreapTests.swift

[Swift 4] Update Treap

---

Z-Algorithm/ZetaAlgorithm.playground/Contents.swift

Update Z Algorithm to Swift 4
#507

[Swift 4] Update Z Algorithm

---

Threaded Binary Tree/ThreadedBinaryTree.playground/Contents.swift

Update Threaded Binary Tree to Swift 4
#507

[Swift 4] Update Threaded Binary Tree

---

Ternary Search Tree/TST.playground/Contents.swift
Ternary Search Tree/Tests/TernarySearchTreeTests.swift
Ternary Search Tree/Tests/Tests.xcodeproj/project.pbxproj
Ternary Search Tree/Tests/Tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata

Update Ternary Search Tree to Swift 4
#507

[Swift 4] Update Ternary Search Tree

---

Slow Sort/SlowSort.playground/Contents.swift
Slow Sort/SlowSort.playground/Sources/SlowSort.swift
Slow Sort/SlowSort.playground/contents.xcplayground
Slow Sort/SlowSort.playground/playground.xcworkspace/contents.xcworkspacedata
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Update Slow Sort to Swift 4
#507

[Swift 4] Update Slow Sort

---

Skip-List/SkipList.playground/Contents.swift
Skip-List/SkipList.playground/Sources/SkipList.swift
Skip-List/SkipList.playground/contents.xcplayground
Skip-List/SkipList.playground/playground.xcworkspace/contents.xcworkspacedata
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Update Skip List to Swift 4
#507

[Swift 4] Update Skip List

---

Shunting Yard/ShuntingYard.playground/Contents.swift
Shunting Yard/ShuntingYard.playground/Sources/Stack.swift

Update Shunting Yard to Swift 4
#507

[Swift 4] Update Shunting Yard

---

Rootish Array Stack/RootishArrayStack.playground/Contents.swift
Rootish Array Stack/Tests/RootishArrayStackTests.swift
Rootish Array Stack/Tests/Tests.xcodeproj/project.pbxproj

Update Rootish Array Stack to Swift 4
#507

[Swift 4] Update Rootish Array Stack

---

QuadTree/QuadTree.playground/Contents.swift
QuadTree/README.md

Updated QuadTree to Swift 4 & Xcode 9.0b5. No code changes needed, only minor spelling change to README file. To solve issue #507

[Swift 4] Update QuadTree

---

Strassen Matrix Multiplication/StrassensMatrixMultiplication.playground/Contents.swift

Update Strassen Matrix Multiplication to Swift 4
#507

[Swift 4] Update Strassen Matrix Multiplication

---

Array2D/README.markdown

Improved description [skip ci]

---

LRU Cache/LRUCache.playground/Contents.swift

[Swift 4] Update LRU Cache

---

Ordered Set/OrderedSet.playground/Pages/Example 1.xcplaygroundpage/Contents.swift
Ordered Set/OrderedSet.playground/Pages/Example 1.xcplaygroundpage/timeline.xctimeline

[Swift 4] Update Ordered Set

---

Linked List/README.markdown

Add `tail = node` to update tail.

Update reverse function in LinkedList

---

.travis.yml
Quicksort/Tests/QuicksortTests.swift
Quicksort/Tests/Tests-Quicksort.xcodeproj/project.pbxproj
Quicksort/Tests/Tests-Quicksort.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Quicksort/Tests/Tests-Quicksort.xcodeproj/xcshareddata/xcschemes/Tests-Quicksort.xcscheme
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

The build error is caused by QuickSort(https://github.com/raywenderlich/swift-algorithm-club/pull/580/commits/449b14b904c6cee06460c3933b7b73f60104593a). The update changed something in workspace, it specified the fileRef as user's local path. So Travis cannot figure out that path, it cause build error.
#604

[Bug] Fix build error

---

Minimum Spanning Tree (Unweighted)/MinimumSpanningTree.playground/Pages/Minimum spanning tree example.xcplaygroundpage/Contents.swift

[Swift 4] Update Minimum Spanning Tree(unweighted)

---

MinimumCoinChange/Tests/MinimumCoinChangeTests/MinimumCoinChangeTests.swift

[Swift 4] Update Minimum Coin Change

---

Priority Queue/Tests/PriorityQueueTests.swift
Priority Queue/Tests/Tests.xcodeproj/project.pbxproj

[Swift 4] Update Priority Queue

---

Radix Sort/RadixSort.playground/Contents.swift
Radix Sort/Tests/RadixSortTests.swift
Radix Sort/Tests/Tests.xcodeproj/project.pbxproj

[Swift 4] Update Radix Sort

---

Red-Black Tree/RedBlackTree.playground/Contents.swift
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

[Swift 4] Update Red Black Tree

---

Multiset/Multiset.playground/Contents.swift
Multiset/Multiset.playground/Sources/Multiset.swift
Multiset/README.markdown

- Improves the README with better examples
- Adds a constructor for instantiating the set with a Collection of Hashasbles

Improvements to Multiset

---

Select Minimum Maximum/SelectMinimumMaximum.playground/Contents.swift

[Swift 4] Update Select Minimum Maximum

---

Shell Sort/Tests/ShellSortTests.swift
Shell Sort/Tests/Tests.xcodeproj/project.pbxproj

[Swift 4] Update Shell Sort

---

Shortest Path (Unweighted)/ShortestPath.playground/Pages/Shortest path example.xcplaygroundpage/Contents.swift
Shortest Path (Unweighted)/Tests/ShortestPathTests.swift
Shortest Path (Unweighted)/Tests/Tests.xcodeproj/project.pbxproj

[Swift 4] Update Shortest Path (Unweighted)

---

Graph/Graph.xcodeproj/project.pbxproj
Single-Source Shortest Paths (Weighted)/SSSP.playground/Contents.swift
Single-Source Shortest Paths (Weighted)/SSSP.xcodeproj/project.pbxproj
Single-Source Shortest Paths (Weighted)/SSSPTests/SSSPTests.swift

[Swift 4] Update Single-Source Shortest Paths (Weighted)

---

Dijkstra Algorithm/Dijkstra.playground/Contents.swift
Dijkstra Algorithm/VisualizedDijkstra.playground/Contents.swift
Dijkstra Algorithm/VisualizedDijkstra.playground/timeline.xctimeline
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

* Update Dijkstra to Swift 4
* Add Dijkstra project into workspace
#507

[Swift 4] Update Dijkstra

---

Bit Set/BitSet.playground/Contents.swift
Bit Set/BitSet.playground/Sources/BitSet.swift
Bit Set/BitSet.playground/timeline.xctimeline
Bit Set/BitSet.swift

Update Bit Set to Swift 4
#507

[Swift 4] Update Bit Set

---

Stack/Stack.swift

Minor update due to Swift changed in the makeIterator function.

Syntax Updates

---

Insertion Sort/README.markdown

Swap changed from swap(&a[y - 1], &a[y])  ->  a.swapAt(y - 1, y)

Swap changes

---

Kth Largest Element/README.markdown

Updated the sort() function to sorted() based on Swift syntax changes.

Minor Change

---

Run-Length Encoding/README.markdown

Missing a curly Brace, opps.

---

Radix Sort/radixSort.swift

tracking the largest value in the array on the first iteration of the bucket sort allows you to do one less loop and drops the need for a `done` variable.
also updated the bucket initialization to use the `(repeatingElement: count:)` initializer and switched to using an iterator for looping through the buckets instead of accessing them based on the range loop.

update to radix sort

---

Merge Sort/MergeSort.playground/Contents.swift
Merge Sort/MergeSort.swift

Modifying the merge method in Merge Sort:
* empty array definition.
* unifying the while loop.
- [*] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [*] This pull request is complete and ready for review.

Code Refactoring

---

Dijkstra Algorithm/Dijkstra.playground/Sources/Dijkstra.swift

Algorithm doesn't work because of usage of incorrect set of vertices.

Correct typo

---

Ring Buffer/RingBuffer.playground/Contents.swift
Ring Buffer/RingBuffer.swift

- Added array private extension to wrap indexes;
- Added Sequence conformance;
- Simplified read and write implementations;
- When reading, value is nilled-out.

Ring Buffer Refinements

---

Selection Sampling/README.markdown
Selection Sampling/SelectionSampling.playground/Contents.swift
Selection Sampling/SelectionSampling.swift

This PR applies the fixes described in #475 to the Selection Sampling algorithm.

edit Selection Sampling for clarity as described in #475

---

Big-O Notation.markdown

Fixes #632. It improves the Big-O Notation.markdown by providing code snippets to better understand the topic.

Updated Big-O Notation.markdown

---

Two-Sum Problem/README.markdown
Two-Sum Problem/Solution 1/2Sum.playground/Contents.swift
Two-Sum Problem/Solution 1/2Sum.playground/contents.xcplayground

The Two Sum problem is defined as, "given an array of integers and an integer target, return the indices of two numbers that add up to the target".
The previous implementation for Two Sum used "the difference between the current number and the target" as the key to a dictionary tracking all the previous numbers in an array. My implementation uses the "current number" as the dictionary key.
This makes the solution easier to reason about. I've updated the readme to match.

Use a simpler dictionary to solve Two Sum.

---

Singly Linked List/SinglyLinkedList.playground/Contents.swift

- I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- This pull request is complete and ready for review.
Fixed typo: becuase -> because

Fixed typo

---

All-Pairs Shortest Paths/README.markdown

I fixed some of minor typos and the inconsistent usage of complexity symbol.

Minor typos of All-pairs Shortest Paths README

---

Dijkstra Algorithm/README.md

Adresses #641 if discussion ends up in favor of my suggestion in that issue.

add astar reference in readme

---

3Sum and 4Sum/README.md

Add syntax color for 3sum-4sum code in Readme

---

Depth-First Search/Tests/DepthFirstSearchTests.swift

Fixes compile errors due to a accidental renaming of `Graph`

Fixes the tests.

---

Singly Linked List/README.markdown

This PR fixes the position of the opening brace in the Singly Linked List's README to conform to the swift style guide.

Fix the position of the opening brace to conform to the style guide

---

Merge Sort/README.markdown
Selection Sort/README.markdown

Lines 40 and 244 in Merge Sort article.
Line 22 in Selection Sort article.

Fix typos in Merge Sort and Selection Sort articles

---

Selection Sort/README.markdown

Update README code to Swift 4

---

Rabin-Karp/README.markdown
Rabin-Karp/Rabin-Karp.playground/Contents.swift

Fixes a few typos and fixes 'characters' is deprecated warning

Rabin karp updates

---

Depth-First Search/DepthFirstSearch.playground/Sources/Graph.swift

Fixes warning by adding @discardableResult to method

Fix warning: Result of call to 'addNode' is unused

---

Splay Tree/readme.md

Small typo in the read me file, caught it while reading about splay trees 🌲

Fixed typo in the README for the word 'example'

---

README.markdown

change the `probablistic` to `probabilistic`
There is a spelling mistake in readme.markdown file
The mistake in section `Lists`->`Skip-List`

Fix a spelling mistake

---

Encode and Decode Tree/EncodeAndDecodeTree.playground/Contents.swift
Encode and Decode Tree/EncodeAndDecodeTree.playground/Sources/EncodeAndDecodeTree.swift
Encode and Decode Tree/EncodeAndDecodeTree.playground/contents.xcplayground
Encode and Decode Tree/EncodeAndDecodeTree.swift
Encode and Decode Tree/readme.md
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Encode and Decode A Binary Tree

Encode and Decode A Binary Tree

---

Binary Search Tree/README.markdown
Kth Largest Element/README.markdown
Selection Sampling/README.markdown

Find a element in array at position of k, should use a[k-1]
update the code in article same as the source code
Fix the mistake in  Selection Sampling

Fix some issues in Kth Largest Element && Selection Sampling article

---

Longest Common Subsequence/README.markdown

Fixed typo in markdown, per commit message.

Fix typo: bottom-left -> bottom-right

---

Combinatorics/README.markdown

Update Combinatorics to match Swift 4 API

---

Splay Tree/readme.md

Fixed broken youtube link in splay tree tutorial [Issue 677]

---

Binary Search Tree/README.markdown

Fixes for typos: function implementation didn't same name as in function call (in Readme file)

change function name for future code explanations

---

Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.swift
Linked List/Tests/LinkedListTests.swift

List of changes:
- Removed several assert and force unwrapping.
- Reworked property var head: Node?
- Removed unnecessary self.
- Default for replaced to forEach

Refactors LinkedList implementation to be more Swifty.

---

README.markdown

Add missing link of **Simulated annealing** to README file.

Add Simulated annealing to README

---

Binary Tree/BinaryTree.swift

Single argument function types require parentheses

[Swift 4 Update]add parentheses

---

Simulated annealing/simann.swift
Simulated annealing/simann_example.swift

\### Checklist
Updated code based on Xcode 10 beta version.  This is not the current version supported by SAC but in case we move towards Xcode 10 in the future, this is here.
Asking the original issue opener to review this.

Fixes Issue#371: Simulated Annealing demo crashes

---

Insertion Sort/InsertionSort.playground/Contents.swift
Insertion Sort/InsertionSort.playground/contents.xcplayground
Insertion Sort/InsertionSort.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Insertion Sort/InsertionSort.swift
Insertion Sort/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

added a convenience method to use when T is comparable, thus not needing a comparison closure.
added also primitive documentation for the methods.

Insertion sort improvements

---

Binary Search/BinarySearch.playground/Contents.swift
Binary Search/BinarySearch.playground/contents.xcplayground

No migration needed for Binary Search

[Swift 4.2] Update Binary Search

---

Shuffle/README.markdown
Shuffle/Shuffle.playground/Contents.swift
Shuffle/Shuffle.playground/Sources/Shuffle.swift

Shuffle algorithm updated to Swift 4.2. Changed random() function to Int.random()
#748

[Swift 4.2] Update Shuffle

---

Stack/Stack.playground/Contents.swift
Stack/Stack.playground/contents.xcplayground

Removed Xcode 9 code snippet from playground file. No other changes needed to migrate to Swift 4.2 - code compiles correctly with Xcode 10 and README.md is up to date.

[Swift 4.2] Update Stack

---

Z-Algorithm/README.markdown
Z-Algorithm/ZAlgorithm.swift
Z-Algorithm/ZetaAlgorithm.playground/Contents.swift
Z-Algorithm/ZetaAlgorithm.swift

Contribution to issue #748
Updated working with strings to Swift 4.2.

[Swift 4.2] Update Z-Algorithm

---

Deque/Deque-Simple.swift
Deque/Deque.playground/Contents.swift
Deque/README.markdown

Contribution to issue #748
Updated `atIndex:` to `at:`.

[Swift 4.2] Update Deque

---

Strassen Matrix Multiplication/StrassensMatrixMultiplication.playground/Contents.swift

Removed notice, did not need any other changes.

[Swift 4.2] Update Strassen Multiplication Matrix

---

Ordered Array/OrderedArray.playground/Contents.swift

Ran playground in Swift 4.2 and verified it's working as expected. 

[Swift 4.2]Update Ordered Array

---

Bubble Sort/MyPlayground.playground/Contents.swift
Bubble Sort/MyPlayground.playground/Sources/BubbleSort.swift
Bubble Sort/MyPlayground.playground/contents.xcplayground
Bubble Sort/MyPlayground.playground/playground.xcworkspace/contents.xcworkspacedata
Bubble Sort/MyPlayground.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Bubble Sort/README.markdown
Bucket Sort/BucketSort.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Added a playground with the Bubble Sort algorithm

Bubble sort algorithm correction and readme improvements

---

GCD/GCD.playground/Contents.swift

Contribution to issue #748
Just removed notice: `// last checked with Xcode 9.0b4`. Don't need any other changes.

[Swift 4.2] Update GCD

---

Fixed Size Array/FixedSizeArray.playground/Contents.swift

Contribution to issue #748
Just removed notice: `// last checked with Xcode 9.0b4`. Don't need any other changes.

[Swift 4.2] Update Fixed Size Array

---

.travis.yml
Karatsuba Multiplication/KaratsubaMultiplication.playground/Contents.swift
Karatsuba Multiplication/KaratsubaMultiplication.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Karatsuba Multiplication/KaratsubaMultiplication.swift
Karatsuba Multiplication/README.markdown
Karatsuba Multiplication/Tests/KaratsubaMultiplicationTests.swift
Karatsuba Multiplication/Tests/Tests.xcodeproj/project.pbxproj
Karatsuba Multiplication/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Karatsuba Multiplication/Tests/Tests/Info.plist
swift-algorithm-club.xcworkspace/contents.xcworkspacedata

Changed the way the characters in a String were accessed since `characters` was deprecated on Swift 4.0.
Removed the code snippet at the beggining of the file.
Updated the `README.md` for the algorithm.
Added a test project with a test based on the example in the `README.md`.

[Swift 4.2] Update Karatsuba Multiplication

---

Selection Sort/SelectionSort.playground/Contents.swift
Selection Sort/SelectionSort.playground/Sources/SelectionSort.swift
Selection Sort/SelectionSort.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

added a convenience method to use when T is not comparable.
added also primitive documentation for the methods

Select sort improvements

---

Bit Set/BitSet.playground/Contents.swift
swift-algorithm-club.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

- [ X] This pull request is complete and ready for review.
Removed last version notice, code runs correctly with no modifications.

Updated Bit Set to Swift 4.2

---

QuadTree/QuadTree.playground/Contents.swift

No migration needed for Quad Tree.

[Swift 4.2] Update Quad Tree

---

AVL Tree/AVLTree.playground/Contents.swift

- [ X] This pull request is complete and ready for review.
Removed notice and the code ran successfully with no changes.

[Swift 4.2] AVL Tree

---

Dijkstra Algorithm/Dijkstra.playground/Contents.swift
Dijkstra Algorithm/Dijkstra.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Dijkstra Algorithm/VisualizedDijkstra.playground/Contents.swift
Dijkstra Algorithm/VisualizedDijkstra.playground/Sources/Window.swift
Dijkstra Algorithm/VisualizedDijkstra.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Dijkstra Algorithm

---

Trie/ReadMe.md
Trie/Trie/Trie.xcodeproj/project.pbxproj
Trie/Trie/Trie.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Trie/Trie/Trie/AppDelegate.swift
Trie/Trie/Trie/Trie.swift
Trie/Trie/Trie/ViewController.swift
Trie/Trie/TrieTests/TrieTests.swift
Trie/Trie/TrieUITests/TrieUITests.swift

Updates Trie to Swift 4.2, as part of #748. Removes `#if swift(>=4.0)` checks and calls to deprecated `String.characters` property, and enables Xcode 10 recommended warnings.

[Swift 4.2] Update Trie

---

Binary Tree/BinaryTree.playground/Contents.swift
Binary Tree/BinaryTree.playground/contents.xcplayground
Binary Tree/BinaryTree.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Updates Binary Tree to Swift 4.2

[Swift 4.2] Updated Binary Tree to Swift 4.2

---

Multiset/Multiset.playground/Contents.swift

No migration needed for Multiset.

[Swift 4.2] Update Multiset

---

Merge Sort/MergeSort.playground/Contents.swift
Merge Sort/MergeSort.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Merge Sort

---

Threaded Binary Tree/ThreadedBinaryTree.playground/Contents.swift
Threaded Binary Tree/ThreadedBinaryTree.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Threaded Binary Tree

---

Knuth-Morris-Pratt/KnuthMorrisPratt.playground/Contents.swift

- [ X] This pull request is complete and ready for review.
Removed notice from code and removed deprecated string .characters method calls.

[Swift 4.2] Updated Knuth-Morris-Pratt 

---

Fizz Buzz/FizzBuzz.playground/Contents.swift
Fizz Buzz/FizzBuzz.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

There was no need to update the source code, simply removed the code snippet.
There was no need to update the source code, simply removed the code snippet.

[Swift 4.2] Update Fizz Buzz

---

Linked List/LinkedList.playground/Contents.swift
Linked List/LinkedList.playground/contents.xcplayground

Removed code snippet from playground file checking for Swift version >= 4.0. 
No other changes needed to migrate to Swift 4.2 
No changes needed to README.md as it is up to date.

[Swift 4.2] Update LinkedList

---

Egg Drop Problem/EggDrop.playground/Contents.swift
Egg Drop Problem/EggDrop.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Egg Drop Problem/EggDrop.playground/playground.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Contribution to issue #748 
No changes needed

[Swift 4.2] Update Egg Drop Problem

---

Two-Sum Problem/README.markdown
Two-Sum Problem/Solution 1/2Sum.playground/Contents.swift
Two-Sum Problem/Solution 1/2Sum.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Two-Sum Problem/Solution 2/2Sum.playground/Contents.swift
Two-Sum Problem/Solution 2/2Sum.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] 2 Sum Problem

---

DiningPhilosophers/DiningPhilosophers.xcodeproj/project.pbxproj
DiningPhilosophers/DiningPhilosophers.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
DiningPhilosophers/README.md

Contribution to #748.
No changes needed.

[Swift 4.2] Dining Philosophers

---

Monty Hall Problem/MontyHall.playground/Contents.swift

No migration needed for Monty Hall.

[Swift 4.2]Update Monty Hall

---

Huffman Coding/Huffman.playground/Contents.swift

No migration needed for Huffman Coding.
PR related to #748.

[Swift 4.2] Update Huffman Coding

---

Ring Buffer/RingBuffer.playground/Contents.swift

No migration needed for Ring Buffer.

[Swift 4.2]Update Ring Buffer

---

Minimum Spanning Tree/MinimumSpanningTree.playground/Contents.swift
Minimum Spanning Tree/MinimumSpanningTree.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

No migration needed for Swift 4.2. References #748.

[Swift 4.2] Updated Minimum Spanning Tree

---

LRU Cache/LRUCache.playground/Contents.swift
LRU Cache/LRUCache.playground/playground.xcworkspace/contents.xcworkspacedata
LRU Cache/LRUCache.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

No migration needed for Swift 4.2. References #748.

[Swift 4.2] Updated LRU Cache

---

Stack/Stack.playground/Contents.swift

This might be overkill for such a small file, but I wish I started using Swift Markdown early in my iOS career. Option click is too convenient to ignore!
I have added an inspectable headerdoc with an example use case. I've also documented all methods and variables.

Added Markdown Documentation to Stack playground

---

Miller-Rabin Primality Test/MRPrimality.playground/Contents.swift
Miller-Rabin Primality Test/MRPrimality.playground/playground.xcworkspace/contents.xcworkspacedata
Miller-Rabin Primality Test/MRPrimality.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

References #748
There were no necessary code changes for Swift 4.2.
Removed the  snippet requested

[Swift 4.2] Update Miller-Rabin Primality Test

---

Bubble Sort/README.markdown

add link to merge sort algorithm in buble sort algorith README.md file

---

Union-Find/UnionFind.playground/Contents.swift
Union-Find/UnionFind.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Updates union-find to swift 4.2

update union-find to swift 4.2

---

Boyer-Moore-Horspool/BoyerMooreHorspool.playground/Contents.swift
Boyer-Moore-Horspool/BoyerMooreHorspool.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Boyer-Moore-Horspool/BoyerMooreHorspool.playground/timeline.xctimeline
Boyer-Moore-Horspool/BoyerMooreHorspool.swift
HaversineDistance/HaversineDistance.playground/Contents.swift

Swift 4.2 Boyer-Moore-Horspool update.
A little code change: characters - an instance property of String, is deprecated.

[Swift 4.2] Update Boyer-Moore-Horspool & HaversineDistance

---

HaversineDistance/HaversineDistance.playground/Contents.swift

The Swift version check has been removed

[Swift 4.2]-Cleans up Haversine playground

---

Boyer-Moore-Horspool/BoyerMooreHorspool.playground/Contents.swift

Removes the Swift check in the playground.

[Swift 4.2] Removes Swift check in Boyer-Moore-Horsepool 

---

Red-Black Tree/README.markdown
Red-Black Tree/RedBlackTree.playground/Contents.swift
Red-Black Tree/RedBlackTree.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

No changes needed, except for removing the code snippet.
Contribution to #748.

[Swift 4.2] Red-Black Sort

---

Hash Set/HashSet.playground/Contents.swift
Hash Set/HashSet.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
swift-algorithm-club.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Updated Hash Set

---

Sorted Set/SortedSet.playground/Pages/Example 1.xcplaygroundpage/Contents.swift

No migration needed for Sorted Set.

Update Sorted Set to Swift 4.2

---

Bit Set/BitSet.playground/Contents.swift
Bit Set/BitSet.playground/contents.xcplayground
Bit Set/BitSet.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Update BitSet to Swift 4.2

---

Heap/Tests/HeapTests.swift
Heap/Tests/Tests.xcodeproj/project.pbxproj
Heap/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Heap/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

[Swift 4.2] Updated Heap

---

Hash Table/HashTable.playground/Contents.swift
Hash Table/HashTable.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

[Swift 4.2] Updated Hash Table

---

Heap Sort/Tests/HeapSortTests.swift
Heap Sort/Tests/Tests.xcodeproj/project.pbxproj
Heap Sort/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Heap Sort/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

[Swift 4.2] Updated Heap Sort

---

Bounded Priority Queue/BoundedPriorityQueue.playground/Contents.swift
Bounded Priority Queue/BoundedPriorityQueue.playground/contents.xcplayground
Bounded Priority Queue/BoundedPriorityQueue.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Bounded Priority Queue/Tests/Tests.xcodeproj/project.pbxproj
Bounded Priority Queue/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Update Bounded Priority Queue to use Swift 4.2

[Swift 4.2] Update Bounded Priority Queue to Swift 4.2

---

Count Occurrences/CountOccurrences.playground/Contents.swift

Playground works with Swift 4.2 without errors

[Swift 4.2] Count occurrences

---

Minimum Edit Distance/MinimumEditDistance.playground/Contents.swift
Minimum Edit Distance/README.markdown

Updated Minimum Edit Distance Playground for Swift 4.2. Only change was removed deprecated `String.characters` usage.
For issue #748.

[Swift 4.2] Updated Minimum Edit Distance Playground for Swift 4.2

---

Bubble Sort/MyPlayground.playground/Contents.swift
Bubble Sort/MyPlayground.playground/Sources/BubbleSort.swift

Added a new method that takes a array of elements that don't need to be Comparable and can receive whatever sorting method, creating the possibility to sort elements in descending order with just two more characters.

addition of convenience method

---

Run-Length Encoding/RLE.playground/Contents.swift

Updated Run-Length Encoding to Swift 4.2. No code changes required.
Part of #748.

Updated Run-Length Encoding to Swift 4.2

---

Comb Sort/README.markdown

- [√] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [√] This pull request is complete and ready for review.
There is an error in Comb Sort description, the name of O(n^2) should be polynomial, not expotential. This PR fixes that, also adding naming for o(n logn) -- quasilinear

Fixed error in description

---

Convex Hull/README.md

Fixes a typo in Convex Hull README

Fix Typo in Convex Hull

---

Convex Hull/README.md

Fix typo in Convex Hull README

---

3Sum and 4Sum/3Sum.playground/Contents.swift
3Sum and 4Sum/3Sum.playground/playground.xcworkspace/contents.xcworkspacedata
3Sum and 4Sum/3Sum.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
3Sum and 4Sum/4Sum.playground/Contents.swift
3Sum and 4Sum/4Sum.playground/playground.xcworkspace/contents.xcworkspacedata
3Sum and 4Sum/4Sum.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Checked for compatibility with Swift 4.2/Xcode 10.1. No changes needed.

[Swift 4.2 Migration] 3Sum and 4Sum

---

Insertion Sort/InsertionSort.swift
Linked List/LinkedList.swift

There is wrong description in Linked List and typo in Insertion Sort.
Issue #861

Fix wrong description and typo.

---

Points Lines Planes/Points Lines Planes.xcodeproj/project.pbxproj
Points Lines Planes/Points Lines Planes.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Points Lines Planes/Points Lines Planes/2D/Line2D.swift
Points Lines Planes/Points Lines Planes/2D/Point2D.swift
Points Lines Planes/Points Lines Planes/main.swift
Points Lines Planes/README.md

Implements a few for now 2 data structures a 2DPoint and a Line 
Line's can be made from points 
You can create perpendicular lines
Check on which side of a line a point is. 
I was writing this to improve the Convex Hull code but it might be a nice addition in itself.

[New algorithm] points lines planes

---

Binary Search Tree/Solution 1/BinarySearchTree.playground/Sources/BinarySearchTree.swift

Fixes : #866 
Signed-off-by: bbvch13531 <bbvch13531@gmail.com>

Change return type to brief type.

---

Comb Sort/Tests/CombSortTests.swift
Comb Sort/Tests/Tests.xcodeproj/project.pbxproj
Slow Sort/SlowSort.playground/Contents.swift
Slow Sort/SlowSort.swift

Removes the Swift 4.0 version check from the playground.
Updates the Swift version to 4.2 in the build settings.
#748

[Swift4.2] Update Comb Sort

---

Red-Black Tree/README.markdown
Red-Black Tree/RedBlackTree.playground/Sources/RedBlackTree.swift

- [ x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
Implement getPredecessor() method for RBTreeNode.
Implement getKey() method for RBTreeNode. 
Update docs.

Add getPredecessor() and getKey() methods to RBTreeNode.

---

Heap/README.markdown

Fix minor typo at Heap/README

---

Big-O Notation.markdown

Added an image showing comparison on different Big O computation complexities in a visual graph

added Big O computation comparison graph

---

Big-O Notation.markdown

Need solve two smaller problems in one recursive call

The code of O(2^n) isn't correct which is O(n)

---

Quicksort/Quicksort.playground/Contents.swift
Quicksort/README.markdown

Use swapAt instead of assignment swap in Lomuto's partitioning algorithm.

Use swapAt for Lomuto's partitioning

---

Skip-List/SkipList.playground/Contents.swift
Skip-List/SkipList.playground/Sources/SkipList.swift
Skip-List/SkipList.swift

Seen no use case for this algo, add the use case

fix: add use case

---

Count Occurrences/README.markdown

Typos corrected

---

Fizz Buzz/FizzBuzz.playground/Contents.swift
Fizz Buzz/FizzBuzz.playground/contents.xcplayground
Fizz Buzz/FizzBuzz.playground/playground.xcworkspace/contents.xcworkspacedata
Fizz Buzz/FizzBuzz.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Fizz Buzz/FizzBuzz.swift
Fizz Buzz/README.markdown

- [ X] This pull request is complete and ready for review.
1) Implement guard to ensure the # of turns is >=1 and error message
2) Use built-in method .isMultiple(of:) to improve readability
3) Use switch statement to improve readability

Resolve Issue #931 - Update Fizz Buzz

---

Heap/README.markdown

Added missing word and fixed a typo
Fixed a typo in Heap's README.markdown and added a word for clarity.

Fix: Typos in Heap README.markdown

---

Shuffle/README.markdown

fixes: typo and punctuation

---

Splay Tree/SplayTree.playground/Contents.swift
Splay Tree/SplayTree.playground/Sources/SplayTree.swift
Splay Tree/SplayTree.swift
Splay Tree/readme.md

#659 
Update `remove function` to fix the bugs that causes Infinite loop and unexpected removal value.

fix: SplayTree.remove is broken

---

Counting Sort/CountingSort.playground/Contents.swift
Counting Sort/CountingSort.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Counting Sort/CountingSort.swift
Counting Sort/README.markdown
Counting Sort/Tests/Tests.xcodeproj/project.pbxproj
Counting Sort/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

On step 3 of Counting sort we need to Loop through the array in reverse to keep the stability of the new array
(i.e. 7, is at index 3 and 6, thus in sortedArray the position of 7 at index 3 should be before 7 at index 6
Also updated Tests project to support Swift 5

Updating Counting Sort for stability

---

Insertion Sort/InsertionSort.swift

declare 'index' as variable

---

Bloom Filter/BloomFilter.playground/Contents.swift

There is a commnet which is describing the output of that line. But the comment is wrong , its written true, but it can be true/false which cant be determined

#986-corrected the comment
