- Heap/Heap.swift
- Heap/HeapTests.swift
- Heap/README.md
- README.markdown
I created a Heap protocol and implemented a MaxHeap. I also included some basic tests. They aren’t exhaustive by any means but I used them to verify everything is working correctly.
> Added Heap

- Select Minimum Maximum/Maximum.swift
- Select Minimum Maximum/Minimum.swift
- Select Minimum Maximum/MinimumMaximumPairs.swift
- Select Minimum Maximum/README.markdown
- Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/MaximumTests.swift
- Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/MinimumTests.swift
- Select Minimum Maximum/SelectMinimumMaximum Tests/SelectMinimumMaximumTests/SelectMinimumMaximumTests.swift
- Select Minimum Maximum/SelectMinimumMaximum.playground/Contents.swift
I've updated the algorithms to handle empty lists. This means the algorithm will return nil when given an empty list which matches the behaviour of the Swift library.
Do you think this should be included? It means we have to add a guard to each algorithm which increases the complexity. I'm not 100% sure if this pull request should be included.
> Handling empty lists when selecting minimum maximum

- .travis.yml
- Longest Common Subsequence/LongestCommonSubsequence.playground/Contents.swift
- Longest Common Subsequence/LongestCommonSubsequence.playground/contents.xcplayground
- Longest Common Subsequence/LongestCommonSubsequence.playground/timeline.xctimeline
- Longest Common Subsequence/LongestCommonSubsequence.swift
- Longest Common Subsequence/README.markdown
- Longest Common Subsequence/Tests/LongestCommonSubsquenceTests.swift
- Longest Common Subsequence/Tests/Tests.xcodeproj/project.pbxproj
- Longest Common Subsequence/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
- Longest Common Subsequence/Tests/Tests/Info.plist
Adds Longest Common Subsequence algorithm. Still need to work on the README.
> Implement Longest Common Subsequence

- Linked List/LinkedList.swift
Using of strong references for both `next` and `previous` properties leads to retain cycle. So `LinkedList.removeAll()` doesn't lead to deallocation of `LinkedListNode` objects.
> Fixing deallocation of LinkedListNode

- Boyer-Moore/README.markdown
Successor of #93.
I added a short introduction of [Boyer-Moore–Horspool algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore%E2%80%93Horspool_algorithm) in `README.md`.
Here are some references for this topic:
- [Horspool_1980.pdf](http://www.cin.br/~paguso/courses/if767/bib/Horspool_1980.pdf)
- [Raita_1992.pdf](http://www.di.ufpe.br/~paguso/courses/if767/bib/Raita_1992.pdf)
- [Boyer-Moore algorithm](http://www.inf.fh-flensburg.de/lang/algorithmen/pattern/bmen.htm)
- [Horspool algorithm](http://www-igm.univ-mlv.fr/~lecroq/string/node18.html)
@hollance 
I found myself hard to write a good README (need some teaching skill :sweat_smile:).
It would be great if you can improve explanation of this algorithm!
> [Boyer-Moore] Add Boyer-Moore-Horspool algorithm

- Shortest Path (Unweighted)/README.markdown
../Minimum Spanning Tree/
=>
../Minimum Spanning Tree (Unweighted)/
> fix broken link

- Quicksort/Quicksort.playground/Contents.swift
- Quicksort/Quicksort.playground/timeline.xctimeline
- Quicksort/Quicksort.swift
- Quicksort/README.markdown
This changes the Quicksort algorithm to use Swift's guard statement to be more consistent to other algorithms in this repository.
> use swift guard statement consistently

- Graph/Graph/AdjacencyListGraph.swift
- Graph/Graph/AdjacencyMatrixGraph.swift
- Graph/Graph/Graph.swift
- Graph/GraphTests/GraphTests.swift
Added graph function to get edges from a vertex – implemented both in AdjacencyMatrixGraph and AdjacencyListGraph.
Needed for graph algorithms.
> Graph: Out Edges from vertex

- Array2D/Array2D.swift
**Problem:**
With te current implementation of the array is possible to accidentally modify the information of an index without accessing directly to it. Ex:
```
//Initial State
var my2DArray = Array2D(columns: 3, rows: 3, initialValue: 0)
// [0 0 0]
// [0 0 0]
// [0 0 0]
//Set a value for the coordinate [1 , 1]
my2DArray[1, 1] = 1
// [0 0 0]
// [0 1 0]
// [0 0 0]
//Set a value for an invalid coordinate [4, 0]
my2DArray[4, 0] = 5
// [0 0 0]
// [0 5 0]
// [0 0 0]
```
As you can see the 5 overwrite the 1 in the matrix by entering an invalid index for the columns parameter.
**Solution:**
Add precondition validations to prevent accessing to out of range indexes. This way we can get proper error handling while using this implementation.
> Added preconditions to subscript to avoid unwanted changes or crashes.

- Count Occurrences/CountOccurrences.playground/Contents.swift
- Count Occurrences/CountOccurrences.swift
- Count Occurrences/README.markdown
> Update Count Occurrences to Swift 3

- Kth Largest Element/kthLargest.playground/Contents.swift
- Kth Largest Element/kthLargest.playground/playground.xcworkspace/xcshareddata/kthLargest.xcscmblueprint
- Kth Largest Element/kthLargest.playground/timeline.xctimeline
> Update to Swift3

- Depth-First Search/DepthFirstSearch.playground/Pages/Simple Example.xcplaygroundpage/Contents.swift
- Depth-First Search/DepthFirstSearch.playground/Pages/Simple Example.xcplaygroundpage/timeline.xctimeline
- Depth-First Search/DepthFirstSearch.playground/Sources/Edge.swift
- Depth-First Search/DepthFirstSearch.playground/Sources/Graph.swift
- Depth-First Search/DepthFirstSearch.playground/Sources/Node.swift
- Depth-First Search/DepthFirstSearch.swift
- Depth-First Search/README.markdown
> migrating dfs to swift3

- Radix Tree/RadixTree.playground/Sources/RadixTree.swift
- Radix Tree/RadixTree.swift
> migrating radix-tree to swift3

- Longest Common Subsequence/README.markdown
Hi! 
I found `reverse()` method was not updated to `reversed()` in README.markdown, so I updated it.
Thanks :)
> Fix method name from reverse() to reversed() in README.markdown

- Tree/README.markdown
- Tree/Tree.playground/Contents.swift
- Tree/Tree.swift
Caused by retain cycle between parent and child (parent has a strong reference to child, and child has a strong reference to parent).
Related to #92.
> Fix memory leak in Tree implementation

- Queue/Queue.playground/Contents.swift
IMHO, making peek a computed property feels _swiftier_
> Made Peek() a computed property

- Array2D/README.markdown
- Deque/Deque-Optimized.swift
- Deque/README.markdown
update Array2D, Deque to swift3.0
> update Array2D, Deque to swift3.0

- Queue/Queue.playground/Contents.swift
- Queue/Queue.playground/timeline.xctimeline
- Queue/README.markdown
@hollance made a remark about this before, and Knuth's Fundamental Algorithms book p. 241 also refers to the first and last items in a queue as front and rear:
"_With queues, we speak of the front and the rear of the queue._"
This updates the `README` and playground files to reflect these changes.
> Modified the peek property name to front

- .travis.yml
- Boyer-Moore/BoyerMoore.playground/Contents.swift
- Boyer-Moore/BoyerMoore.swift
- Boyer-Moore/README.markdown
- Boyer-Moore/Tests/BoyerMooreHorspoolTests.swift
- Boyer-Moore/Tests/BoyerMooreTests.swift
- Boyer-Moore/Tests/Info.plist
- Boyer-Moore/Tests/Tests.xcodeproj/project.pbxproj
- Boyer-Moore/Tests/Tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Boyer-Moore/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- Boyer-Moore/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
This is what I did:
- added some unit tests
- ensure every test pass
- added Boyer-Moore-Horspool algorithm (previously mentioned in the README but don't implemented) with tests.
- added me in the credits section ;)
This fixes #284.
> Boyer-Moore algorithm updates

- Binary Search Tree/Solution 2/BinarySearchTree.playground/Contents.swift
- Binary Search Tree/Solution 2/BinarySearchTree.playground/Sources/BinarySearchTree.swift
- Binary Search Tree/Solution 2/BinarySearchTree.swift
- Counting Sort/CountingSort.playground/Contents.swift
- Counting Sort/CountingSort.swift
- Linked List/README.markdown
- Shunting Yard/ShuntingYard.playground/Contents.swift
- Shunting Yard/ShuntingYard.swift
update enum case uppercase to lowercase 
- playground
- README.md
- some.swift file
> Updating to Swift3 (enum lowercase)

- Queue/Queue.playground/Contents.swift
- Queue/Queue.playground/timeline.xctimeline
- Queue/README.markdown
- Stack/README.markdown
- Stack/Stack.playground/Contents.swift
This change is inspired by the Swift naming conventions guide and Knuth's fundamental algorithms book page 242 where he states the element at the top of the stack may be denoted by top(A) where A is the stack.
> Modified Stack peek property to front

- Huffman Coding/Huffman.playground/Contents.swift
- Huffman Coding/Huffman.playground/Sources/Heap.swift
- Huffman Coding/Huffman.playground/Sources/Huffman.swift
- Huffman Coding/Huffman.playground/Sources/NSData+Bits.swift
- Huffman Coding/Huffman.playground/Sources/PriorityQueue.swift
- Huffman Coding/Huffman.playground/timeline.xctimeline
- Huffman Coding/Huffman.swift
- Huffman Coding/NSData+Bits.swift
- Huffman Coding/README.markdown
> Migrated Huffman Coding to Swift 3 syntax

- Ternary Search Tree/TernarySearchTree.swift
- Ternary Search Tree/Tests/TernarySearchTreeTests.swift
The problem was that the testdata generator could sometimes (but not on every test run...) generate keys that was not unique...which caused the `find` method to return the wrong values for keys when more keys existed in the tree with the same value.
> fixing failing test on Ternary Search Tree

- Queue/Queue-Optimized.swift
- Queue/Queue-Simple.swift
- Queue/README.markdown
- Queue/Tests/QueueTests.swift
- Stack/README.markdown
- Stack/Stack.swift
- Stack/Tests/StackTests.swift
Hi Swift Algorithm Club team!
This PR has the following changes. Can I ask you to review them? Thanks 😃
- Stack and Queue's `peek()` method was replaced with `top` and `front` properties with #322 PR. This PR updates Stack.swift, StackTests.swift, Queue-Simple.swift, Queue-Optimized.swift, and QueueTests.swift to use the changes.
- Fix Queue-Optimized front property implementation in Queue/README.markdown.
- Fix indentation in Stack/README.markdown.
> Update Stack and Queue files to use top and front properties

- .travis.yml
- Radix Sort/RadixSort.playground/Contents.swift
- Radix Sort/RadixSort.playground/Sources/radixSort.swift
- Radix Sort/RadixSort.playground/contents.xcplayground
- Radix Sort/RadixSort.playground/playground.xcworkspace/contents.xcworkspacedata
- Radix Sort/Tests/Info.plist
- Radix Sort/Tests/RadixSortTests.swift
- Radix Sort/Tests/Tests.xcodeproj/project.pbxproj
- Radix Sort/Tests/Tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Radix Sort/Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
- Radix Sort/radixSort.swift
Also added a playground and test.
> Convert RadixSort to swift3 syntax

- .travis.yml
- Binary Search Tree/README.markdown
- Binary Search Tree/Solution 1/BinarySearchTree.playground/Sources/BinarySearchTree.swift
- Binary Search Tree/Solution 1/Tests/BinarySearchTreeTests.swift
- Binary Search Tree/Solution 1/Tests/Tests.xcodeproj/project.pbxproj
- Binary Search Tree/Solution 1/Tests/Tests.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- Binary Search Tree/Solution 2/BinarySearchTree.playground/Contents.swift
- Fix Issue: left/right tree should reconnect to new node
- Test: unmark .travis.yml test
- Lint files
- Update README.markdown
> Update Binary search tree

- Trie/Trie/Trie/Trie.swift
- Trie/Trie/TrieTests/TrieTests.swift
Solves issue #378 
`findWordsWithPrefix` finds all words starting with a prefix. Includes prefix if it's a word stored in the trei. Returns all words if prefix = "" 
Added unit test.
> Trie - Support prefix matching

- Deque/Deque-Optimized.swift
- Deque/README.markdown
The trimming is now done by keeping in mind the original capacity of the queue, thus ensuring the queue will keep at least its original capacity.
A wrong index in the README has been corrected too.
> Fixed the trimming of deques

- Binary Tree/BinaryTree.swift
Hello, I was recreating this file in playground and I noticed you still had the explicit @noescape . Thought I can lend a hand by removing it. Thanks for this awesome repository!
> Updated syntax for Swift 3

- Queue/README.markdown
Fixes links to Linked List, Ring Buffer, and Priority Queue directories.
[Rendered](https://github.com/jkrmr/swift-algorithm-club/blob/a54e722b035ffc5eeba63fcd5b1648e56f732ec0/Queue/README.markdown):
_____________________________________________
There are many other ways to create a queue. Alternative implementations use a [linked list](../Linked%20List/), a [circular buffer](../Ring%20Buffer/), or a [heap](../Heap/). 
Variations on this theme are [deque](../Deque/), a double-ended queue where you can enqueue and dequeue at both ends, and [priority queue](../Priority%20Queue/), a sorted queue where the "most important" item is always at the front.
> Fix links to related articles

- README.markdown
fixed broken link in importants link sections.
> fixed important links section link

- AVL Tree/README.markdown
- Big-O Notation.markdown
- Binary Search Tree/README.markdown
- Binary Search/README.markdown
- Binary Tree/README.markdown
- Bloom Filter/README.markdown
- Bounded Priority Queue/README.markdown
- Boyer-Moore/README.markdown
- Breadth-First Search/README.markdown
- Count Occurrences/README.markdown
- Hash Set/README.markdown
- How to Contribute.markdown
- Ordered Array/README.markdown
- Ordered Set/README.markdown
- Selection Sort/README.markdown
- Shell Sort/README.markdown
- Shortest Path (Unweighted)/README.markdown
- Threaded Binary Tree/README.markdown
- Topological Sort/README.markdown
- Tree/README.markdown
- Under Construction.markdown
There are a ton of broken markdown links in the READMEs throughout this repo because the files and directories they refer to have spaces in their names but these aren't HTML encoded in their links. This commit just replaces spaces with %20 to fix these.
before:
after:
before:
after:
> URL encode links in Markdown files

- Graph/README.markdown
Few of the links in the "Graph" section had white spaces in its addresses, this PR has these links fixed.
** Markdown does not identify links with spaces (i.e `../Linked List/`) as URLs. All white space characters need to be replaced with `%20` to be encoded properly (i.e `../Linked%20List/`).
> Updated Graph/README.markdown

- Linked List/LinkedList.playground/Contents.swift
- Linked List/LinkedList.swift
This PR address 2 issues in the Linked List files:
- The playground had few wrong comments about the expected output of the statements
- The implementation of the Linked List has a logical error where a `Node` is used as is when passed to the `append` or `insert` functions. The correct way of implementing such functions is to ALWAYS copy the node's value into a new node, and then insert the new node into the data structure.
Without the second fix, a simple statement like `list.append(list.first)` would crash the playground if the list has more than 1 node (`last.next` won't be `nil` in this case)
> Fixing a bug in the Linked List logic

- .swiftlint.yml
Fix "found unknown escape character" while trying to run swiftlint 0.18.1
Also updated the smiley face regex check to have a space before the colon so that it doesn't match the following line: 
fatalError("init(coder:) has not been implemented")
Fixes the following error while trying to run swiftlint:
error: scanner: while parsing a quoted scalar in line 20, column 12
found unknown escape character:
regex: "(\:\))"
> Fix error while trying to run swiftlint

- DiningPhilosophers/README.md
Fixed a few typos in DiningPhilosophers Readme
an -> a
dinining -> dining
"no needs" -> "no need"
> Fix a few typos in DiningPhilosophers Readme

- Hashed Heap/HashedHeap.swift
- Hashed Heap/README.markdown
- Hashed Heap/Tests/Hashed Heap Tests.xcodeproj/project.pbxproj
- Hashed Heap/Tests/Hashed Heap Tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Hashed Heap/Tests/Hashed Heap Tests.xcodeproj/xcshareddata/xcschemes/Hashed Heap Tests.xcscheme
- Hashed Heap/Tests/HashedHeapTests.swift
- Hashed Heap/Tests/Info.plist
- swift-algorithm-club.xcworkspace/contents.xcworkspacedata
Even though there already is a PR for an A* implementation, that PR implements it in O(bN^2) instead of the optimal O(bn). This data structure is the necessary building block for an optimal implementation. It is just a variation on the existing regular heap, but adding a hash map for fast lookups by value.
> Add hashed heap data structure

- Binary Search Tree/README.markdown
- Binary Search Tree/Solution 1/BinarySearchTree.playground/Sources/BinarySearchTree.swift
- LRU Cache/LRUCache.playground/Sources/LinkedList.swift
- Linked List/LinkedList.swift
- Linked List/README.markdown
- Threaded Binary Tree/ThreadedBinaryTree.playground/Sources/ThreadedBinaryTree.swift
This set of changes removes redundant use of the optional binding ```swift case let _?``` statement. It also updates the matching explanations. 
before 
```swift
while case let next? = node.next { ...  }
```
after
```swift
while let next = node.next { ...  }
```
> removes redundant case let ? statements from workspace

- Shell Sort/README.markdown
- Shell Sort/Shell Sort.playground/Contents.swift
- Shell Sort/Shell Sort.playground/contents.xcplayground
> [Swift 4] Update Shell Sort

- Egg Drop Problem/EggDrop.playground/Contents.swift
- Egg Drop Problem/EggDrop.playground/Sources/EggDrop.swift
- Egg Drop Problem/EggDrop.playground/contents.xcplayground
- Egg Drop Problem/EggDrop.swift
- Egg Drop Problem/README.markdown
- swift-algorithm-club.xcworkspace/contents.xcworkspacedata
Hello!
I noticed that there aren't many dynamic programming algorithms in the repository, so I decided to contribute to the project by adding one of the most famous problems in dynamic programming "Egg Drop Problem". I'd appreciate if you could look through my code and give some feedbacks.
Thanks in advance for your attention!
> Egg Drop Dynamic Problem

- Two-Sum Problem/README.markdown
- Two-Sum Problem/Solution 1/2Sum.playground/Contents.swift
Simplifies wording and naming.
> Updated solution 1 for clarity.

- README.markdown
> Update readme for swift 4 and Xcode 9

- GCD/GCD.playground/Contents.swift
- GCD/GCD.swift
- GCD/README.markdown
By changing the arithmetic operation order, we can calculate the least common multiplier correctly for larger integers without overflow.
> Avoid integer overflow in LCM calculation

- Big-O Notation.markdown
Fix capitalized parameter name.
> Fix nonconventional parameter naming in Big-O notation article

- QuadTree/README.md
Fixed a few typos:
Quadrees -> Quadtrees
containts -> contains
Wiki -> Wikipedia
Also my editor automatically removed trailing spaces from empty lines
> Fix a few typos in QuadTree/README.md

- Linked List/LinkedList.playground/Contents.swift
- Linked List/LinkedList.swift
- Linked List/README.markdown
- Linked List/Tests/LinkedListTests.swift
- [*] I've looked at the contribution guidelines.
- [*] This pull request is complete and ready for review.
* I am confirming that this pull request can merge [#583 Linked list conformance to collection protocol](https://github.com/raywenderlich/swift-algorithm-club/pull/583) and pass the test.
* Modified node(atIndex:) method not to return nil, and code refactoring.
* Deleted nodesBeforeAndAfter(index:) method, and modified insert methods.
* Modified readme file.
> Fixed LinkedList:

- Linked List/LinkedList.playground/Contents.swift
- Linked List/LinkedList.swift
- Linked List/README.markdown
- Linked List/Tests/LinkedListTests.swift
Adds conformance to the standard library's Collection protocol for the LinkedList class.
> Linked list conformance to collection protocol

- Radix Tree/RadixTree.playground/Sources/RadixTree.swift
- Radix Tree/RadixTree.swift
Radix Tree source files updated to Swift 4 syntax.
Characters removed (deprecated in Swift 4). Substring removed (deprecated in Swift 4). String slicing subscript used for substrings creation.
> Swift 4 syntax update

- Introsort/HeapSort.swift
- Introsort/InsertionSort.swift
- Introsort/IntroSort.swift
- Introsort/Introsort.playground/Contents.swift
- Introsort/Introsort.playground/Sources/HeapSort.swift
- Introsort/Introsort.playground/Sources/InsertionSort.swift
- Introsort/Introsort.playground/Sources/Partition.swift
- Introsort/Introsort.playground/Sources/Randomize.swift
- Introsort/Introsort.playground/Sources/Sort3.swift
- Introsort/Introsort.playground/contents.xcplayground
- Introsort/Partition.swift
- Introsort/README.markdown
- Introsort/Randomize.swift
- Introsort/Sort3.swift
- README.markdown
Swift 4 implementation for the Introsort sorting algorithm.
> [New Algorithm] Introsort sorting algorithm

- Binary Search/README.markdown
Replaces example usage of `indexOf(_:)` with `Collection.index(of:)`. The global function `indexOf(_:)` was replaced with `Collection.index(of:)` in Swift 2.
> Replaces references to indexOf(_:) with index(of:).

- Breadth-First Search/README.markdown
Link to shortest path example was broken. I've updated it to what I believe is the page it is meant to point to:
https://github.com/raywenderlich/swift-algorithm-club/tree/master/Shortest%20Path%20(Unweighted)
> Fixed broken link

- Binary Search Tree/README.markdown
- Binary Search Tree/Solution 2/BinarySearchTree.swift
In accordance with the [terminology](https://en.wikipedia.org/wiki/Tree_(data_structure)#Terminology), leaf nodes have height **zero**, and a tree with only a single node (hence both a root and leaf) has height **zero**. Conventionally, an empty tree (tree with no nodes, if such are allowed) has height **−1**.
> [Binary Search Tree] [enum] Fix height

- Rabin-Karp/Rabin-Karp.playground/Contents.swift
- Rabin-Karp/Rabin-Karp.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- [ x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
since `flatMap(_:)` is deprecated for non-nil result, I changed it for `compactMap(_:)`
> Fix Rabin-Karp warnings

- Linked List/README.markdown
Near the bottom of the Linked List README there is a short section on alternate approaches. The alternate approach described is to use an `enum` instead of a `class`. In the paragraph following though there was a typo where it referred to the "class-based" version instead of this new "enum-based" version.
Along with fixing that typo I've also expanded that paragraph to include the reasoning for why a copy is made and included a link to Apple's blog post around value and reference types.
> Fixes typo in Linked List README - class to enum

- Linear Search/LinearSearch.playground/Contents.swift
The code worked fine in Xcode 10. I removed code snippet at the top of playground file.
> [Swift 4.2] Updated Linear Search

- Linked List/LinkedList.playground/Contents.swift
The code worked fine in Xcode 10. I removed code snippet at the top of playground file.
> [Swift 4.2] Updated Linked List

- Linear Regression/LinearRegression.playground/Contents.swift
- Linear Regression/README.markdown
I've confirmed that the linear regression playground still works with Swift 4.2. I also removed a warning by renaming an unused loop variable to `_`.
> [Swift 4.2] Confirmed Linear Regression to work with Swift 4.2

- Selection Sort/SelectionSort.playground/Contents.swift
- Selection Sort/SelectionSort.playground/Sources/SelectionSort.swift
The code worked fine in Xcode 10. I removed code snippet at the top of playground file and fixed error in SelectionSort.swift
> [Swift 4.2] Updated Selection Sort

- GCD/GCD.playground/Contents.swift
- GCD/GCD.playground/Sources/GCD.swift
- GCD/GCD.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- GCD/GCD.playground/timeline.xctimeline
- GCD/GCD.swift
- GCD/README.markdown
* Three different approaches for the GCD to be calculated
* Improves the LCM by passing the used GCD algorithm into the function.
* Find an easy GCD function if possible.
* Adopts the changes in the appropriate README file.
> Adds binary recursive stein algorithm to the GCD class

- Merge Sort/README.markdown
reserveCapacity was missing in README for Merge Sort despite being present in the sample code. 
In my tests, reserving capacity unconditionally right after creating array for merging worked best, sorting a shuffled array with 1 million integers in 11.6% less time.  
Even though it doesn't reduce time complexity, I think that a simple line of code that has so much effect on efficiency should not be omitted. And removing reserveCapacity when required capacity is known precisely in advance is certainly not very _Swift_'y.
> reserveCapacity missing in README for MergeSort

- Linear Regression/README.markdown
In the description of the linear regression (iterative) there an error in the formula.
This function `J` is proportional to `((slope * carAge + intercept) - carPrice)) ^ 2`.
not `((slope.carAge + intercept) - carPrice)) ^ 2`!
> Fixed error in linear regression formula

- .github/CONTRIBUTING.md
Fixed a few simple typos and grammar mistakes at Contributing Guidelines.
> Fix typo and grammar

- Hash Table/HashTable.playground/Sources/HashTable.swift
- Hash Table/README.markdown
This fixes the unlikely event that the generated hashValue happens to be equal to Int.min (can that even happen?), in which case the abs value of it would be Int.max + 1 causing overflow.
> Fix abs of hashValue causing overflow

- Count Occurrences/CountOccurrences.playground/Contents.swift
- Count Occurrences/CountOccurrences.swift
- Count Occurrences/README.markdown
This PR makes a few minor improvements to the Count Occurrences algorithm.  Most notably, it rewrites the definition to constrain the algorithm to Comparable types (instead of just Integers) and improves some documentation and semantics.
> Improvements to Count Occurrences

- Knuth-Morris-Pratt/README.markdown
The link from the Knuth-Morris-Pratt README to the Boyer-Moore String Search page was broken due to a name change. I just fixed the broken link.
> Fixed Link to Boyer-Moore String Search from Knuth-Morris-Pratt README

- Topological Sort/TopologicalSort1.swift
Fixes infinite recursion in the DFS algorithm for topological sort caused by graphs with cycles. 
For example the following graph would previously have recursed indefinitely `a->b->a`.
Fixes issue where a cyclical DAG would recurse indefinitely.
> Fix infinite recursion in DFS

- Heap/Heap.swift
Heap documentation inside the Swift file states that removing a node is a O(n log n) operation. This is incorrect. 
- Finding the node in the heap: O(n)
- Removing the node at a particular index: O(log n)
O(n) + O(log n) reduces to O(n).
> updating incorrect big-O performance documentation of heap removal

- Heap/Heap.swift
Time complexity of remove() is O(n + log n), which simplifies to O(n).
Fixes incorrect time complexity.
> Fix incorrect time complexity

- Heap Sort/README.markdown
"No contribution is too small", I fixed a single character typo in the Heap Sort README. (First open source contribution ever 🙂)
> Fix typo in Heap Sort README lg -> log

- Graph/Graph/Edge.swift
- Graph/Graph/Vertex.swift
- [ x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
This PR resolves the `'Hashable.hashValue' is deprecated as a protocol requirement` by updating both the `Vertex` and `Edge` structures to  `implementing 'hash(into:)' instead`.
There are many other instances of this warning that need to be addressed but I believe those should be updated on a case by case basis to help keep PR's as small and concise as possible 😁
> updated depricated hashable values to hash into methods

- Knuth-Morris-Pratt/KnuthMorrisPratt.swift
Just wanted to update the syntax from Array(self.characters) to Array(self). Similarly for casting of the ptnr String.
> Updating how String can be casted into an Array.

- Insertion Sort/InsertionSort.playground/Contents.swift
- Insertion Sort/InsertionSort.playground/contents.xcplayground
- Insertion Sort/InsertionSort.swift
- README.markdown
> Insersion sort: rename variables with convenience names

- Longest Common Subsequence/LongestCommonSubsequence.playground/Contents.swift
* updated longest common subsequence string extension to access `String` directly, not through `charchaters`.
* updated header to reflect last version of Xcode checked on
> fix: updated LCS string extension to access string directly

- Linked List/README.markdown
Linked List is very commonly used with recursive approach as using recursion makes the process simpler and reduces the complexity of the code. So this is a code snippet of reversing a singly linked list using recursion. Hope it is useful!
> final README

- Selection Sampling/README.markdown
- Selection Sampling/SelectionSampling.swift
Correction of the README.markdown and Selection Sampling code improvement #998
This PR addresses two main aspects:
1. Correction in the README.markdown: 
Edited and clarified certain sections of the documentation for better readability and comprehension.
Updated example code snippets to reflect more efficient or clearer implementation in the context of selection sampling.
2. Improvement to the Selection Sampling Code:
Optimized the current implementation by reducing the time complexity of key operations.
Refactored parts of the algorithm to improve maintainability and readability.
Added comments for better code understanding and to adhere to the coding standards of the repository.
> issue resolved  #997 and #998
